num_frames = 4
n_actions = 4
c = 1e-2
dirichlet_alpha = [4, 4, 4, 4]
dir_noise_weight = 0.5
adam_lr = 1e-3
move_temp_initial = 0.01
move_temp = 0.01
state_dim = (64, 64, 4) # four frame history
max_number_of_rounds_per_game = 5000
num_games_to_play = 100
planning_depth = 200
num_generations = 100
num_evaluation_games = 5
is_to_augment_data = 1
num_epochs = 400
batch_size = 64
test_size = 0.2
is_to_plot = 1
save_res_dir = 'enter path for generation plots- training and validation curves'
generation_folder_path = 'enter path for generational training data'
model_folder_path = 'enter path for saving generational model weights'
